type Query {
  avos: [Avocado]!
  avo(id: ID!): Avocado
}

type Mutation {
  createAvo(data: AvoCreateInput!): Avocado!
}

"""
Avocados
"""
interface BaseModel {
  id: ID!
  createdAt: String!
  updatedAt: String
  deletedAt: String
}

type Attributes {
  description: String
  shape: String
  hardiness: String
  taste: String
}

type Avocado implements BaseModel {
  id: ID!
  createdAt: String!
  updatedAt: String
  deletedAt: String

  name: String!
  sku: String!
  price: Float!
  image: String!
  attributes: Attributes!
}

input AvoCreateInput {
  name: String!
  price: Float!
  image: String!
  description: String
  shape: String
  hardiness: String
  taste: String
}
